- name: Remove existing Docker packages if any
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  ignore_errors: true

- name: Install required apt dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker APT repository
  ansible.builtin.shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt and install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Copy docker dir correctly
  copy:
    src: "/home/ubuntu/ASPA-lab/docker/"
    dest: "/opt/aspa-lab/docker"
    mode: "0755"
    remote_src: false
    directory_mode: "0755"

- name: Copy conf dir
  copy:
    src: "/home/ubuntu/ASPA-lab/conf/"
    dest: "/opt/aspa-lab/conf"
    mode: "0755"
    remote_src: false
    directory_mode: "0755"

- name: Copy ca dir
  copy:
    src: "/home/ubuntu/ASPA-lab/ca/"
    dest: "/opt/aspa-lab/ca"
    mode: "0755"
    remote_src: false
    directory_mode: "0755"

- name: Copy rp dir
  copy:
    src: "/home/ubuntu/ASPA-lab/rp/"
    dest: "/opt/aspa-lab/rp"
    mode: "0755"
    remote_src: false
    directory_mode: "0755"

- name: Build and run docker-compose
  command: docker compose up -d
  args:
    chdir: /opt/aspa-lab/docker

